name: Simple File Copy
on: [push, pull_request, workflow_dispatch]
jobs:
  run:
    runs-on: [self-hosted]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Make copy of test.txt
      run: |
        chmod u+x "${GITHUB_WORKSPACE}/files/copyfile.sh"
        bash "${GITHUB_WORKSPACE}/files/copyfile.sh"
